apiVersion: v1
kind: ConfigMap
metadata:
  name: opencanary-config
data:
  opencanary.conf: |
    {
        "device.node_id": "mtd-honeypot-01",
        "ip.ignorelist": [],
        "git.enabled": false,
        "http.enabled": true,
        "http.port": 8000,
        "http.skin": "basicAuth",
        "logger": {
            "class": "PyLogger",
            "kwargs": {
                "formatters": {
                    "plain": {
                        "format": "%(message)s"
                    }
                },
                "handlers": {
                    "console": {
                        "class": "logging.StreamHandler",
                        "stream": "ext://sys.stdout"
                    }
                }
            }
        },
        "mysql.enabled": true,
        "mysql.port": 3306,
        "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
        "ssh.enabled": true,
        "ssh.port": 22,
        "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
        "ftp.enabled": true,
        "ftp.port": 21,
        "ftp.banner": "FTP server ready",
        "telnet.enabled": true,
        "telnet.port": 23,
        "telnet.banner": "\\ntelnet server ready\\n\\nlogin: "
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencanary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencanary
  template:
    metadata:
      labels:
        app: opencanary
    spec:
      containers:
      - name: opencanary
        image: thinkst/opencanary:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 22
          name: ssh
        - containerPort: 21
          name: ftp
        - containerPort: 23
          name: telnet
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: opencanary-config
          mountPath: /etc/opencanaryd/opencanary.conf
          subPath: opencanary.conf
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]
      volumes:
      - name: opencanary-config
        configMap:
          name: opencanary-config
---
apiVersion: v1
kind: Service
metadata:
  name: opencanary-service
  #namespace: mtd-system
spec:
  selector:
    app: opencanary
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: ssh
    port: 22
    targetPort: 22
  - name: ftp
    port: 21
    targetPort: 21
  - name: telnet
    port: 23
    targetPort: 23
  - name: mysql
    port: 3306
    targetPort: 3306
  type: Nodeport  # Change to LoadBalancer if using a cloud provider