apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtd-controller-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mtd-controller-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtd-controller-role-binding
subjects:
- kind: ServiceAccount
  name: mtd-controller-account
roleRef:
  kind: Role
  name: mtd-controller-role
  apiGroup: rbac.authorization.k8s.io